# This schema is used by both client and server
# It specifies the GraphQL queries exchanged between them

type Species {
    id: String!,
    name: String!,
    image: String!
}

type Flower {
    id: String!,
    speciesId: String!,
    plotId: String
}

type Point {
    x: Int!,
    y: Int
}

type Plot {
    id: String!,
    name: String!,
    corners: [Point!]!,
    slots: [Point!]
}